import { useState } from "react";
import type { CastDocument } from "../../domain/contracts/cast";
import type { ArtDocument } from "../../domain/contracts/art";
import { compileCharacterSheetJob, compilePropSheetJob, compileSceneSheetJob } from "../../flow/jobs/image-job-compiler";
import type { FlowAspectRatio, FlowJobManifest, FlowOutputCount } from "../../flow/jobs/types";

export function AssetStudioView({ cast, art, projectId, sourceDocumentVersion, imageModel, defaultAspectRatio = "16:9", onQueue }: { cast?: CastDocument; art?: ArtDocument; projectId: string; sourceDocumentVersion: number; imageModel: string; defaultAspectRatio?: FlowAspectRatio; onQueue: (jobs: FlowJobManifest[]) => void }) {
  const [notice, setNotice] = useState("");
  const [selectedImageModel, setSelectedImageModel] = useState(imageModel);
  const [aspectRatio, setAspectRatio] = useState<FlowAspectRatio>(defaultAspectRatio);
  const [outputCount, setOutputCount] = useState<FlowOutputCount>(1);
  const context = { projectId, sourceDocumentVersion, imageModel: selectedImageModel, aspectRatio, outputCount };
  const queue = (job: FlowJobManifest) => { onQueue([job]); setNotice(`已加入 ${job.kind}：${job.sourceEntityId} · ${job.modelName} · ${job.aspectRatio} · ${job.outputCount ?? 1} 張`); };
  const queueCharacter = (character: CastDocument["characters"][number]) => {
    try { queue(compileCharacterSheetJob(character, context)); } catch (error) { setNotice(error instanceof Error ? error.message : "人物素材 prompt 不完整，無法加入佇列"); }
  };
  return <><div className="section-kicker">03 / ASSET STUDIO</div><h2 className="page-title">把世界拆成<br/><em>可綁定的素材。</em></h2><p className="lede">內容管線的 canonical visual prompt 會原樣保存；下方內建三視圖版型 prompt 會與人物描述合成後送入 Flow 佇列。</p><div className="form-card asset-settings"><div className="card-label">IMAGE JOB SETTINGS</div><div className="field-grid"><label>圖片模型<input value={selectedImageModel} onChange={(event) => setSelectedImageModel(event.target.value)} placeholder="例如：Nano Banana 2" /></label><label>比例<select value={aspectRatio} onChange={(event) => setAspectRatio(event.target.value as FlowAspectRatio)}><option value="16:9">16:9</option><option value="9:16">9:16</option></select></label><label>張數<select value={outputCount} onChange={(event) => setOutputCount(Number(event.target.value) as FlowOutputCount)}><option value={1}>1 張</option><option value={2}>2 張</option><option value={3}>3 張</option><option value={4}>4 張</option></select></label></div></div>{notice && <div className="import-notice">{notice}</div>}<div className="stage-list">{(cast?.characters ?? []).map((character) => <article className="output-card" key={character.id}><h3>{character.name} <small>{character.id}</small></h3><div className="prompt-label">人物描述</div><p>{typeof character.persona === "string" ? character.persona : JSON.stringify(character.persona)}</p><div className="prompt-label">CANONICAL VISUAL PROMPT</div><pre className="asset-prompt">{character.image.prompt || "尚未產生 canonical visual prompt；請重新執行美術資產階段。"}</pre><div className="prompt-label">THREE-VIEW PROMPT</div><pre className="asset-prompt">{character.image.sheetPrompt || "尚未產生三視圖 prompt；請重新執行美術資產階段。"}</pre><button className="primary-button" disabled={!character.image.prompt?.trim() || !character.image.sheetPrompt?.trim() || !selectedImageModel.trim()} onClick={() => queueCharacter(character)}>在 Flow 生成三視圖 →</button></article>)}{(art?.scenes ?? []).map((scene) => <article className="output-card" key={scene.id}><h3>{scene.name} <small>{scene.id}</small></h3><p>{scene.imagePrompt}</p><button className="primary-button" onClick={() => queue(compileSceneSheetJob(scene, context))}>在 Flow 生成場景 →</button></article>)}{(art?.props ?? []).map((prop) => <article className="output-card" key={prop.id}><h3>{prop.name} <small>{prop.id}</small></h3><p>{prop.imagePrompt}</p><button className="primary-button" onClick={() => queue(compilePropSheetJob(prop, context))}>在 Flow 生成道具 →</button></article>)}</div></>;
}
