import type { StoredJobRecord } from "../../storage/job-store";

const jobKindLabels: Record<string, string> = { "character-sheet": "人物三視圖", "scene-sheet": "場景素材", "prop-sheet": "道具素材", "storyboard-frame": "分鏡畫面", "veo-segment": "影片片段" };
const jobStatusLabels: Record<string, string> = { pending: "待處理", preflight: "前置檢查", configuring: "設定中", "binding-assets": "綁定素材", submitting: "提交中", waiting: "等待結果", capturing: "擷取中", validating: "驗證中", completed: "已完成", paused: "已暫停", retrying: "重試中", failed: "失敗", cancelled: "已取消", "needs-user-selection": "等待使用者選擇" };
const jobKindLabel = (kind: string) => jobKindLabels[kind] || kind;
const jobStatusLabel = (status: string) => jobStatusLabels[status] || status;

export function JobStatusCard({ job, running = false, onExecute, onRemove, onPause, onResume, onRetry, onCancel }: { job: StoredJobRecord; running?: boolean; onExecute?: () => void; onRemove?: () => void; onPause?: () => void; onResume?: () => void; onRetry?: () => void; onCancel?: () => void }) {
  const displayName = job.manifest?.sourceEntityName || job.sourceEntityId;
  const assetNames = job.manifest?.assetNames || [];
  return <article className="output-card job-status-card"><div className="job-card-header"><h3>{jobKindLabel(job.kind)} <small>{displayName}</small></h3><span className={`stage-state job-${job.status}`}>{jobStatusLabel(job.status)}</span></div><p>模型：{job.modelName} · 畫面比例：{job.aspectRatio}{job.outputCount ? ` · ${job.outputCount} 張` : ""}{job.durationSec ? ` · ${job.durationSec} 秒` : ""}</p>{assetNames.length > 0 && <p><b>本鏡自動加入素材</b>：{assetNames.join("、")}</p>}<p className="muted">作業檢查點：{jobStatusLabel(job.checkpoint)} · 嘗試次數：{job.attempts} · 輸出數量：{job.outputAssetIds.length}</p>{job.prompt && <details className="job-prompt-details"><summary>查看送入 Flow 的完整提示詞</summary><pre>{job.prompt}</pre>{job.promptMetadata?.characterDescription && <><div className="prompt-label">人物描述</div><p>{job.promptMetadata.characterDescription}</p></>}{job.promptMetadata?.visualPrompt && <><div className="prompt-label">標準視覺提示詞</div><pre>{job.promptMetadata.visualPrompt}</pre></>}{job.promptMetadata?.sheetPrompt && <><div className="prompt-label">三視圖提示詞</div><pre>{job.promptMetadata.sheetPrompt}</pre></>}{job.negativePrompt && <><div className="prompt-label">負面提示詞</div><pre>{job.negativePrompt}</pre></>}</details>}{job.error && <div className="generation-error">{job.error}</div>}<div className="form-actions">{onExecute && job.manifest && !["completed", "cancelled"].includes(job.status) && <button className="text-button" onClick={onExecute} disabled={running}>單獨執行</button>}{job.status === "paused" && <button className="text-button" onClick={onResume}>繼續</button>}{job.status === "waiting" && <button className="text-button" onClick={onPause}>暫停</button>}{job.status === "failed" && <button className="text-button" onClick={onRetry}>重試</button>}{!["completed", "cancelled"].includes(job.status) && <button className="text-button" onClick={onCancel}>取消</button>}{onRemove && <button className="text-button danger-button" onClick={onRemove} disabled={running}>移除</button>}</div></article>;
}
